### ISSUE TITLE
Mod on alpha 20.6 (b9) - not working corectly

### ISSUE THREAD

**Issue by ErythroCraft** [OCB7D2D/OcbRemoteDescription#1]
Hello

I installed your mod at my server with OcbPlantGrowInfo , too.

So. The server starts, but on client side  EAC is blocking the client to join.
EAC says, the server send custom data or clients must install mods.

What can I do without disabeling EAC ?

**Comment by mgreter** [comment]
Client and server need the mod and both need EAC disabled.

**Comment by ErythroCraft** [comment]
ok. But disabeling EAC is not a chance.
We'll not use your mods.

Thanks for infos
